name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nim-lang/setup-nimble-action@v1
        with:
          nimble-version: '0.20.1' # default is 'latest'. You could also use `nightly` to get #HEAD
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run:
          sudo apt-get update
          sudo apt-get install -y qt6-base-dev qt6-base-private-dev qt6-declarative-dev
          nimble build -l
